tasks:
  - name: Install and Setup with Bun
    command: |
      curl -fsSL https://bun.sh/install | bash 
      source /home/gitpod/.bashrc
      bun install
      bun db:generate
      cp .env.local.example .env.local
      bun lang:build
      bun env:sync