tasks:
  - init: curl -fsSL https://bun.sh/install | bash \
      echo 'export BUN_INSTALL="/home/gitpod/.bun"' >> /home/gitpod/.bashrc.d/600-bun | bash && \
      echo 'export PATH="$BUN_INSTALL/bin:$PATH"' >> /home/gitpod/.bashrc.d/600-bun | bash

  - name: Install and Run with bun
    command: bun install && bun db:generate && cp .env.local.example .env.local && bun env:sync && bun dev
